### PR TITLE
ghc 9.2 wip

### PR DESCRIPTION
**Pull request by l29ah**
re https://github.com/ndmitchell/record-dot-preprocessor/issues/42
i've mauled some terms in Compat to typecheck, using the relevant ghc commits as a reference, without much understanding of the semantics involved, but then i'm faced with a much bigger volume of type errors in the preprocessor itself, so i'm not sure i will complete it

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
in case it helps, http://blog.shaynefletcher.org/2021/05/annotations-in-ghc.html gives a summary overview of annotations in 9.2.1

also, depending on your needs, you might get by with the native record dot syntax support offered in that release

**Comment by l29ah** [comment]
I've checked the native record dot syntax, but it's really incomplete, and seemingly won't make it into 9.2 in such an useful form that record-dot-preprocessor is.

**Comment by ndmitchell** [comment]
Thanks for the code! A very useful start. Any information I could provide that would let you get any further? Or would you prefer to just stop there, and hopefully this can serve as a reference when someone else gives it a go?

**Comment by ndmitchell** [comment]
GHC 9.2 is now out, if @l29ah or someone else wants to pick this up.

**Comment by ndmitchell** [comment]
#50  cleaned this up and finished it off, thanks all!

**Pull request closed without merging**
