### PR TITLE
ghc-9.2 compatibility

### PR DESCRIPTION
**Pull request by sheaf**
This PR adds GHC 9.2 compatibility for the record-dot-preprocessor plugin. It's still WIP as it's not fully backwards compatible yet.

### CODE REVIEW

**Comment by sheaf** [comment]
Thanks to @phadej for cleaning up my mess and finishing up the patch. This should now work across GHC versions up to 9.2.

**Comment by ndmitchell** [comment]
Thanks so much - is this now ready to land? Could you please edit it slightly to encourage the CI to run? (GitHub disabled the CI, but I didn't realise it wasn't going to reenable it when a PR came in...)

**Comment by sheaf** [comment]
> Thanks so much - is this now ready to land? 

I think so, provided CI is happy. What configurations are tested?

**Comment by phadej** [comment]
> First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)

**Comment by sheaf** [comment]
This passes CI now, so it should be good to go.

**Comment by ndmitchell** [comment]
Thanks! Will make a release in the next hour.

**Comment by ndmitchell** [comment]
0.2.15 contains this change

**Pull request merged**
